# config.yaml
problem_id: 1
leetccode_link: https://leetcode.com/problems/global-and-local-inversions/description/
problem_name: "Global and Local Inversions"
problem_statement_file: "challenge1_statement.txt"
solution_file: "challenge1_solution.py"
function_name: "isIdealPermutation" # this is the name of the function that the LLMs will create, should be in the problem statement
input_variables:
  - name: "A"
    type: "list"